name: Deploy Docs XProject

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv venv .venv
          source .venv/bin/activate
          uv pip install mkdocs-material 
          uv add -r requirements.txt  # Ensure requirements.txt exists

      - name: Check MkDocs installation
        run: uv run mkdocs --version

      - name: Build site
        run: uv run mkdocs build --site-dir site

      - name: Debug build output
        run: ls -R site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './site'  # Ensure correct path

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
